---
name : build-test-deploy3
on : push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@vc
    - run: "g++ ./quadratic_solver.cpp -o quadratic_solver.exe"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: "bash quadratic.sh"
